apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cronjob
spec:
  schedule: "*/1 * * * *"  # Runs every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello-container
            image: busybox
            command: ["/bin/sh", "-c", "while true; do echo 'Hello from Kubernetes CronJob!'; sleep 2; done"]
          restartPolicy: Never

